apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  labels:
    app: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
        labels:
          app: yolo
    spec:
      containers:
      - name: yolo
        image: inkcube/int-yolo:dev_v0.2.7
        env:
          - name: REGION
            value: eu-central-1
          - name: S3_BUCKET
            value: k8s-danielms-dev
          - name: TELEGRAM_APP_URL
            value: polybot.dev:8443
          - name: DYNAMO_NAME
            value: prediction-db-tf-dev
          - name: SQS_QUEUE_NAME
            value: danielms-tf-queue-dev

        resources:
#          requests:
#            cpu: 200m
#            memory: 500Mi
#          limits:
#            cpu: 500m
#            memory: 1000Mi